<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master extends CI_Model
{
  public $rtraining = 'rtraining';
  public $id = 'id';
  public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
	function getcalendar(){

		$this->db->select('tanggal, tempat, nama, jam, trainer');
		$this->db->from('mtraining');
		$this->db->order_by('Tanggal');
		$query = $this->db->get();
		return $query->result();
	}

	function getpengumuman($data){
		$this->db->select('id, pengumuman, start, end');
		$this->db->from('mpengumuman');
		$this->db->order_by('start');
		$this->db->where('start <=',$data['start']);
		$this->db->where('end >=',$data['end']);
		$query = $this->db->get();
		return $query->result();

	}

	function getdept($iddept){
	 /* 	if($iddept!=null){
			$kondisi =" where iddept and iddept<>".$iddept;
		}else{
			$kondisi="  where iddept ";
		}

		$query = $this->db->query("select iddept,nama from Mdept");

		return $query->result(); */
		//$this->db->join('mdept', 'mjabatan.iddept = mdept.iddept');
		$this->db->order_by('nama', 'asc');
         return $this->db->get('mdept')->result();
	}

	function getjabatan(){
		 //$this->db->order_by('nama_kota', 'asc');
         $this->db->join('mdept', 'mjabatan.iddept = mdept.iddept');
         return $this->db->get('mjabatan')->result();
	}

	function get_selected_by_idjabatan($idjabatan){
		$this->db->where('idjabatan',$idjabatan);
		$this->db->join('mdept', 'mjabatan.iddept = mdept.iddept');
		return $this->db->get('mjabatan')->row();
	}

	function gettraining(){
		$this->db->order_by('tersedia');
		return $this->db->get('mtraining')->result();
	}

  function reporttraining($id){
    $this->db->where('idtraining',$id);
    return $this->db->get('rtraining')->result();
  }

  function getraport($iduser){
    $this->db->where('iduser',$iduser);
    return $this->db->get('rraport')->result();
  }

  function getuser(){
    return $this->db->get('user')->result();
  }

}

/* End of file Titem_model.php */
/* Location: ./application/models/Titem_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-24 18:22:33 */
/* http://harviacode.com */
