<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mtraining_model extends CI_Model
{

    public $table = 'mtraining';
    public $id = 'idtraining';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idtraining,nama,tempat,tanggal,jam,trainer,kapasitas');
        $this->datatables->from('mtraining');
        //add this line for join
        //$this->datatables->join('table2', 'mtraining.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('mtraining/read/$1'),'Read')." | ".anchor(site_url('mtraining/update/$1'),'Update')." | ".anchor(site_url('mtraining/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'idtraining');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idtraining', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jam', $q);
	$this->db->or_like('trainer', $q);
	$this->db->or_like('kapasitas', $q);
	$this->db->or_like('tersedia', $q);
	$this->db->or_like('terisi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idtraining', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jam', $q);
	$this->db->or_like('trainer', $q);
	$this->db->or_like('kapasitas', $q);
	$this->db->or_like('tersedia', $q);
	$this->db->or_like('terisi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

  

}

/* End of file Mtraining_model.php */
/* Location: ./application/models/Mtraining_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-06-05 06:31:09 */
/* http://harviacode.com */
